version: '3'

services:
  mongodb:
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db
      - /data/mongodb_config:/data/configdb
    container_name: mongodb
    image: mongo
    restart: always
  to_do:
    ports:
      - "4000:4000"
    container_name: to_do
    image: to_do